### ISSUE TITLE
Move Ops setup to this guide

### ISSUE THREAD

**Issue by RogerHuba** [codefellows/setup-guide#115]
Moving from ops-102 repo.

Move Scripts from Dlee repo #52

Previous instructor had repo set up with scripts for setup. Should move these to ops-102 repo.
https://github.com/lee5378/labsetup

**Comment by brookr** [comment]
Djavan started unspooling the script in this PR: https://github.com/codefellows/ops-102-guide/pull/60

**Comment by brookr** [comment]
Please ping @CourtHans for testing when the PR is ready.

**Comment by RogerHuba** [comment]
Closed with #124 
Moving Changes to remove script and do manual install to another Issue.
