### ISSUE TITLE
How to enable copy/paste hotkeys in Windows Subsystem for Linux (WSL) / command prompt (cmd)?

### ISSUE THREAD

**Issue by HexxKing** [codefellows/setup-guide#121]
I'm not sure if this is something you want to add to the setup guide or not but the TAs and I came across a few Window users who could not copy/paste into their Ubuntu. 

Kassie did some digging and found this article. I vaguely remember my high school students needing to do something similar for their Chromebooks too. 

solution source: https://superuser.com/questions/1410026/how-to-enable-ctrl-shift-v-in-windows-subsystem-for-linux-wsl-command-pr

**Comment by RogerHuba** [comment]
Functionality already built in to WSL Ubuntu with right click.
