### ISSUE TITLE
Continue talks about future setup for students

### ISSUE THREAD

**Issue by RogerHuba** [codefellows/setup-guide#139]
Continue discussion on ways to streamline setup.

Talked so far:
GitHub CodeSpaces
AWS EC2

**Comment by DavidSouther** [comment]
GitHub codespaces would be phenomenal, however, it does have an associated cost & requires Github Teams or Enterprise.
That said, it would reduce the setup guide to ~5 minutes...

I'm going to take the opposite tack and suggest that we might not want to streamline setup. I think part of the value we bring students is giving them the real world "just go do it" approach, with guidance. Our grads are much more likely to come across a new hire guide similar to this one (frankly, much _worse_ than ours) than they are to come across a nice, streamlined, one-click VM.

**Comment by johncokos** [comment]
Agree @DavidSouther

**Comment by johncokos** [comment]
Closed as we're leaving WSL on the windows side and moving towards some containerization ...
