### ISSUE TITLE
Document remote-wsl for windows vscode users

### ISSUE THREAD

**Issue by DavidSouther** [codefellows/setup-guide#141]
It looks like remote-wsl was mentioned in the WSL2 conversion guide, but never got into the published guide. https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode for official docs to kitbash from.

**Comment by RogerHuba** [comment]
Check on order of extension install and opening VS Code in terminal after a restart.

**Comment by johncokos** [comment]
@RogerHuba  Where are we on this?
