### ISSUE TITLE
Node.js Installation issues for Windows users.

### ISSUE THREAD

**Issue by akkanben** [codefellows/setup-guide#155]
Homebrew currently only hosts binaries for 64-bit Linux, Intel Macs, and Apple Silicon Macs: [Homebrew Formulae page for Node](https://formulae.brew.sh/formula/node). Even though 64-bit Linux is listed, students using WSL were not able to install the binaries. 

During the latest round of 102 setups Windows users who tried to `brew install node` were greeted with a message that they need to use the `--build-from-source` option because there were not any bottles for their OS. Even with an updated system via apt and having installed `build-essential` we were unable to build from source. There are likely other dependencies required.

We may want to update the guide adding a Windows only set of instructions for installing Node.js via NVM or further instructions on building from source via Homebrew. Previous NVM instructions were replaced with the Homebrew instructions in commit 7dfdf7d7f45d5d8811c338b04db0caf526f107d4. These could be reinstated for Windows users or we could use instructions directly from the NVM GitHub.

Following the instruction from the [NVM GitHub page](https://github.com/nvm-sh/nvm): The installer script `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash` will create the required ~/.nvm directory and clone the nvm repository there. It also will add the NVM_DIR environmental variable to the student's .zshrc. To install Node.js itself students will just need to execute `nvm install` for the latest version or `nvm install --lts` for the latest LTS version. 

The downside to including the script directly would be updating the link as NVM versions are released. Potentially the guide could just link directly to the GitHub readme at the installation heading: [https://github.com/nvm-sh/nvm#installing-and-updating](https://github.com/nvm-sh/nvm#installing-and-updating) and the student could be directed to copy that code snippet -- we could include an image like this to help direct them:

![snippet](https://user-images.githubusercontent.com/4212656/184028110-a55b16d1-381e-4ccf-8267-654a28a41352.png)

**Comment by RogerHuba** [comment]
Closing. This was a once-day issue node installation.
