### ISSUE TITLE
Move away from Windows 10 Jan 1, 2023

### ISSUE THREAD

**Issue by RogerHuba** [codefellows/setup-guide#160]
Version | Start Date | End Date
-- | -- | --
Version 20H2 | Oct 20, 2020 | May 10, 2022
Version 2004 | May 27, 2020 | Dec 14, 2021
Version 1909 | Nov 12, 2019 | May 11, 2021

**Comment by johncokos** [comment]
Because Win 11 requires special hardware, we can't force that this on students just yet, as students may have laptops from 2019 or 2020 still.

**Comment by johncokos** [comment]
We updated all course web pages to not specify a windows version, but are asking for latest.
