### ISSUE TITLE
.zprofile to .zshrc

### ISSUE THREAD

**Issue by kassiebradshaw** [codefellows/setup-guide#163]
Correct bottom of homebrew steps page:

echo 'export BREW_HOME="/home/linuxbrew/.linuxbrew/bin"' >> $HOME/~~.zprofile~~.zshrc
echo 'export PATH="$PATH:$BREW_HOME"' >> $HOME/~~.zprofile~~.zshrc
reset

**Comment by DavidSouther** [comment]
This needs to be updated for 401's postgress step, as well
