### ISSUE TITLE
Simplify Ops virtualbox install 

### ISSUE THREAD

**Issue by brookr** [codefellows/setup-guide#177]
Ethan reported success with a simple `apt install virtualbox` rather than other stuff we are doing with Oracle's version. 

Let's update, and verify we can do it the easy way! 

I'm calling this a P0, because the instructions we currently have didn't work for most students.

**Comment by ewhd** [comment]
The linked PR fixes the last link to David's script.

My next step is running through the setup guide instructions on a VM to make sure everything works and to see what can be stripped out.
