### ISSUE TITLE
Some students are getting WSL 2.0, it messes with node, lets switch to nvm

### ISSUE THREAD

**Issue by ncarignan** [codefellows/setup-guide#18]
Some students are accidentally installing WSL 2.0, i believe this can be seen if their wsl version is 20.x or higher, maybe 18.x
Node was unable to install on about 1/3 of my class' machines. None of the workarounds were reliable. The easiest way to get around / head off this issue is to install node through nvm
https://github.com/nvm-sh/nvm
they run this command for windows
``` curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash ```

this one for mac
``` brew install nvm```
For mac, this article seems to suggest directories must be created. I need a test to be done on a mac to see if these are up to date https://medium.com/@jamesauble/install-nvm-on-mac-with-brew-adb921fb92cc

then all students will run 
``` nvm install node 10 ```

Proposal: switch all students to installing nvm before installing node.

**Comment by brookr** [comment]
New WSL 2 setup is using NVM.
