### ISSUE TITLE
Prework - Oh My Zsh steps need tweaks

### ISSUE THREAD

**Issue by johncokos** [codefellows/setup-guide#194]
From @JB-Tellez 

https://codefellows.github.io/setup-guide/system-setup/mac/5-ohmyzsh.html

When you're otherwise up to date but with a lower version of zsh you are sent to a reinstallation of Oh My Zsh which which is 1) Doesn't fix the problem and 2) Requires students to handle a re-installation scenario.

If student gets past tat the problem still won't be solved and they're instructed to re-export some BREW config variables which don't fix the problem and has students confirm their homebrew set up.

**Comment by kassiebradshaw** [comment]
Modify trying to verify after running installation steps

**Comment by kassiebradshaw** [comment]
Closes with PR #206
