### ISSUE TITLE
zsh setup mac m2

### ISSUE THREAD

**Issue by rkgallaway** [codefellows/setup-guide#205]
zsh was installed, but going to next page did not activate zsh in my terminal.  running the install script DID activate it.  I would advocate for just running the install script regardless and thereby activating base zsh terminal styling with "robbyrussell" theme

<img width="629" alt="image" src="https://github.com/codefellows/setup-guide/assets/40313258/cc907207-c14a-45aa-8730-987f488c621a">

**Comment by kassiebradshaw** [comment]
Working on getting this fixed @rkgallaway!
Closes with PR #206
