### ISSUE TITLE
401 JS Setup

### ISSUE THREAD

**Issue by JB-Tellez** [codefellows/setup-guide#27]
- https://codefellows.github.io/setup-guide/code-401-javascript/1-httpie.html
  - [x] Footer should say “Next” vs. Return Home
- https://codefellows.github.io/setup-guide/code-401-javascript/3-azure.html
  - [x] azure-cli command is 'az' not 'azure'
- https://codefellows.github.io/setup-guide/code-401-javascript/5-mongo.html#mac-users
  - [x] brew services start mongodb-community@4.2 should leave off @4.2 (tested on Mac 10.14.6)
- https://codefellows.github.io/setup-guide/code-401-javascript/5-mongo.html#validate-that-postgres-clients-can-connect
  - [x] Remove erroneous 'postgres'
- https://codefellows.github.io/setup-guide/code-401-javascript/5-mongo.html#linux-and-windows-users
  - [x] Not automatically starting mongod after running steps. Does run manually. Tested on Ubuntu 18

**Comment by brookr** [comment]
Mongo moved to 301 setup, now at v5.

**Comment by brookr** [comment]
Now on Ubuntu 20.

**Comment by brookr** [comment]
All checked off!
