### ISSUE TITLE
WSL2:  Ubuntu sending students to windows mnt on initial load

### ISSUE THREAD

**Issue by rkgallaway** [codefellows/setup-guide#47]
As WSL2 has progressed, bugs and performance issue have escalated for those storing their repos in the Windows File System.  Further WSL2 optimization will more strictly mandate that repos not live in the Windows File System.  To that end, students on Windows machines using WSL2 should be directed to the Ubuntu side of their machine and save files there.  Ideally at `~/home/<username>`  

I would advocate for a two-part process to maximize the student experience:  
1. Implement the change at the 102 level to protect students from ever having a less than ideal windows experience
2. Publish an official instructions page for how to resolve the issue for current 201, 301, and 401 students

Here are instructions that have been proven successful for making that conversion for 301 as of class-02 *if helpful*.  Note that it is not campus agnostic, likely could just include `cd` at bottom of .profile with an appropriate comment, and other language could be optimized as well:
> **ONLY DO THIS IF YOU ARE CURRENTLY SAVING ON THE WINDOWS SIDE OF YOUR MACHINE**
1. ACP from ALL of your 301 repos and merge into main.  this should be your lab, DSA, and Reading I believe
2. in terminal type cd and press enter.  you should see ~$
3. run the command pwd and you should see ~/home/<username> 
4. run the command ls if you do not see a  codefellows directory, create one by running the command mkdir codefellows
5. cd into codefellows, run the command ls if you do not see 301 and 401 directories run the command mkdir 301 401
6. clone your 301 repos into the appropriate places.  I would clone the dsa repo into codefellows, and the gallery of horns into 301
7. Technically at this point you are good, but to find those repos you must always run the cd command FIRST thing when you open Ubuntu.  
8. Here’s a fix for that:  run the command nano ~/.profile it should take you to a different screen and with a bunch of strange looking code.  if it does not and you encounter a permissions issue run sudo nano ~/.profile and enter your Ubuntu password instead.  This should take you to that magical place
9. using your down arrow key to navigate, arrow all the way down.  underneath the last line of code leave an empty space and paste in the following code snippet
```
# ur evaluates to the absolute path to your Ubuntu user's root.
export ur=~/codefellows/
# This gives us a quick way of moving directly to the Ubuntu root
alias cdur='cd "$ur"'
# This brings you to your Ububntu Working directory immediately when you open a new terminal.
cdur
```
10. once this snippet is properly entered, use the command Control X to exit, y to save and enter to finalize this process.  open a new ubuntu and you should see codefellows on the command line!  From here forward you should automatically be brought to this place on the Ubuntu side of your machine where things work more dependably and with greater speed!

**Comment by RogerHuba** [comment]
Fixed with PR #63
