### ISSUE TITLE
301 setup script dsa.sh error due to master/main changes

### ISSUE THREAD

**Issue by lee5378** [codefellows/setup-guide#65]
There's a bad URL that's holding up 301 pre work students from executing the setup script. This looks like a neglected revision due to a recent master > main branch nomenclature changeover. Whoever is making these changes needs to test any related scripts to avoid students encountering this.

Fixed by #64 

Faulting code:
```
#!/bin/bash
# Download and configure the DS&A Repo First
downloadRepo() {
  curl https://codeload.github.com/codefellows/data-structures-and-algorithms/legacy.tar.gz/main --output dsa.tar.gz
  tar zxvf dsa.tar.gz --strip 1
}
```

Error:

```
$ tar zxvf dsa.tar.gz --strip 1
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

The root cause is `https://codeload.github.com/codefellows/data-structures-and-algorithms/legacy.tar.gz/main` pulls down a HTTP error code instead of the actual file. So the next few commands are trying to decompress a text file that just has error text in it.

**Comment by brookr** [comment]
This has been addressed by converting the DSA repo to main: both links now work.
