### ISSUE TITLE
Students Skipping Step in Mongo WSL Config / Install

### ISSUE THREAD

**Issue by bnates** [codefellows/setup-guide#86]
We need additional instructions for students that make sure they complete ALL MongoDB installation instructions. 
 Refer to this issue for more:  https://github.com/codefellows/code-301-guide/issues/281

@4a50 wanna tackle getting some extra notes for students added to ensure that they don't miss this step?

**Comment by dahlbyk** [comment]
Until https://github.com/MicrosoftDocs/WSL/pull/1266 is hopefully merged it might be good to note something to the effect of:

> If **Step 8** still says "Go to your home directory: `cd / && cd home`", you should run `cd ~` instead.
